version: "3.8"
services:
  frontend:
    build: ./frontend
    image: ${DOCKER_HUB_CREDS_USR}/mini-app-frontend:latest
    container_name: mini-app-frontend
    ports:
    - target: 5000
      published: 80
  backend:
    deploy:
      replicas: 1
    build: ./backend
    image: ${DOCKER_HUB_CREDS_USR}/mini-app-backend:latest
    container_name: mini-app-backend
    environment:
      DATABASE_URI:
      CREATE_SCHEMA:

    ports:
    - target: 5000
      published: 5000